/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/knowledge/root": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前知识库根目录(KR)与默认 KR */
        get: operations["getKnowledgeRoot"];
        /** 更换知识库根目录(KR)，并把内容整体迁移到新目录 */
        put: operations["migrateKnowledgeRoot"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/scan": {        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 扫描 KR 目录，索引真实 .md/.txt 与外部文件
         * @description 递归扫描 KR（排除 .trash / .history 及隐藏目录），将真实文件夹建为 gt_knowledge_folders、 真实 .md/.txt 建为 gt_knowledge_documents（按相对路径去重）。并发调用串行化保证幂等。
         */
        post: operations["scanKnowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/documents/{uuid}/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 解析文档 uuid 对应的 KR 内真实绝对路径 */
        get: operations["getDocumentPath"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 文档列表（支持 folder_id / keyword 过滤） */
        get: operations["listDocuments"];
        put?: never;
        /** 新建文档（支持 md / txt） */
        post: operations["createDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/documents/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 UUID */
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        /** 获取文档详情（含正文，按 file_path 从 KR 读取） */
        get: operations["getDocument"];
        /** 更新文档（标题/文件夹变更时同步重命名真实文件） */
        put: operations["updateDocument"];
        post?: never;
        /** 删除文档（软删并移入 .trash） */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/documents/{uuid}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 从回收站恢复文档（真实文件移回原 file_path） */
        post: operations["restoreDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/documents/{uuid}/permanent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 永久删除文档（删除 .trash 与历史真实文件） */
        delete: operations["hardDeleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 文件夹树 */
        get: operations["listFolders"];
        put?: never;
        /** 新建文件夹 */
        post: operations["createFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/folders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文件夹 ID */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /** 更新文件夹（名称/父级，含环检测） */
        put: operations["updateFolder"];
        post?: never;
        /**
         * 删除文件夹（双语义：keep 保留文件 / purge 全部删除）
         * @description body {mode} 必填且必须为 keep|purge；缺省/非法返回 400（不静默沿用旧行为）。 根文件夹（无父）拒绝删除。keep：子树文档上提到父级；purge：文档软删+移入回收站、文件夹与子文件夹删除。
         */
        delete: operations["deleteFolder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 回收站文档列表 */
        get: operations["listTrash"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全文搜索（基于 KR 真实文件内容） */
        get: operations["searchKnowledge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/key/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 配置键（如 knowledge_root_dir） */
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        /** 读取通用配置键值（如 knowledge_root_dir），不存在返回空串 */
        get: operations["getConfigKey"];
        /** 写入通用配置键值（UPSERT gt_client_config） */
        put: operations["putConfigKey"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{uuid}/files/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 把超长引用内容唯一命名落盘到任务产出目录 */
        post: operations["spillTaskReferenceFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description 业务错误码（与 i18n key 对应）
             * @example knowledge_root_not_writable
             */
            code: string;
            /**
             * @description 本地化错误信息（后端实际返回字段名为 error，此处统一为 message）
             * @example 知识库目录不可写或无权限，请选择可写目录
             */
            message: string;
            /** @description 附加数据（如 conflicts / rollback），可为空 */
            data?: Record<string, unknown> | null;
        };
        /** @description 本地 API 统一错误响应（wire 形状）：`error` 为已本地化提示，`code` 为可区分的业务错误码 */
        ErrorResponse: {
            /** @description 本地化错误提示（随 X-GoTeams-Lang / Accept-Language 切换中英） */
            error: string;
            /** @description 业务错误码（通常与 i18n key 同名） */
            code?: string;
        };
        KnowledgeRootMigrateRequest: {
            /** @description 目标知识库根目录（绝对路径，来自原生目录选择） */
            dir: string;
            /**
             * @description 必填；当前仅支持 migrate（执行内容迁移），缺省或非法一律 400
             * @enum {string}
             */
            mode: "migrate";
        };
        /** @description 迁移统计（隐藏目录及其内容不参与 folders/documents 计数） */
        MigrateStats: {
            /** Format: int32 */
            entries: number;
            /** Format: int32 */
            folders: number;
            /** Format: int32 */
            documents: number;
        };
        KnowledgeRootMigrateResponse: {
            /** @description 迁移后的新 KR 绝对路径 */
            root: string;
            migrated: components["schemas"]["MigrateStats"];
        };
        /** @description 同名冲突项（最浅冲突路径，即旧 KR 顶层相对路径） */
        MigrateConflictItem: {
            path: string;
            /** @enum {string} */
            type: "file" | "dir";
        };
        /** @description 迁移失败后的回滚结果 */
        MigrateRollback: {
            /** @description 是否全部回滚成功；false 时前端需列出 failed 提示人工处理 */
            completed: boolean;
            failed: string[];
        };
        KnowledgeRootMigrateConflictError: components["schemas"]["ErrorResponse"] & {
            conflicts: components["schemas"]["MigrateConflictItem"][];
        };
        KnowledgeRootMigrateFailedError: components["schemas"]["ErrorResponse"] & {
            rollback?: components["schemas"]["MigrateRollback"];
        };
        /** @description 超长引用内容落盘请求（S-IN-08） */
        ReferenceSpillRequest: {
            /** @description 来源文档文件名（含扩展名，用于生成落盘文件名；不可为空） */
            file_name: string;
            /** @description 待落盘的引用正文（不可为空；前端按 Unicode 码点判定是否超过 10000） */
            content: string;
        };
        /** @description 超长引用内容落盘结果（S-IN-08 / S-DA-12） */
        ReferenceSpillResponse: {
            /** @description 落盘文件相对任务产出目录的路径（唯一，不覆盖既有文件） */
            path: string;
            /** @description 落盘文件绝对路径（消息体中以此引用产出文件） */
            absolute_path: string;
            /** Format: int32 */
            size: number;
        };
        RootConfig: {
            /** @description 当前生效的 KR 绝对路径 */
            root: string;
            /** @description 默认 KR 绝对路径 */
            default: string;
        };
        ScanResult: {
            /** Format: int64 */
            added_folders: number;
            /** Format: int64 */
            added_documents: number;
        };
        DocumentPath: {
            /** Format: uuid */
            uuid: string;
            /** @description KR 内真实绝对路径；不存在时为空串 */
            absolute_path: string;
            /** @description 文档未删且真实文件存在时为 true */
            exists: boolean;
        };
        Document: {
            /** Format: uuid */
            uuid: string;
            /** Format: int64 */
            folder_id: number;
            title: string;
            /**
             * @description 相对 KR 的真实相对路径（含文件名与扩展名）
             * @example 子文件夹/我的文档.md
             */
            file_path: string;
            /**
             * @description 文档格式
             * @enum {string}
             */
            ext: "md" | "txt";
            tags?: string[];
            /** @description 正文（仅详情/创建接口返回） */
            content?: string;
            content_hash?: string;
            /** Format: int64 */
            word_count?: number;
            /** Format: int64 */
            created_at?: number;
            /** Format: int64 */
            updated_at?: number;
        };
        FolderNode: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            parent_id: number;
            /** Format: int64 */
            created_at?: number;
            /** Format: int64 */
            updated_at?: number;
            children?: components["schemas"]["FolderNode"][];
        };
        SearchResult: {
            /** Format: uuid */
            uuid: string;
            title: string;
            snippet: string;
            /** Format: int64 */
            folder_id: number;
        };
    };
    responses: {
        /** @description 服务器内部错误 */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description 文档 UUID */
        Uuid: string;
        /** @description 文件夹 ID */
        Id: number;
        /** @description 配置键（如 knowledge_root_dir） */
        Key: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getKnowledgeRoot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description 当前生效的 KR 绝对路径
                         * @example C:/Users/me/AppData/knowledge/root
                         */
                        root: string;
                        /** @description 默认 KR 绝对路径（<profileDir>/knowledge/root） */
                        default: string;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    migrateKnowledgeRoot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeRootMigrateRequest"];
            };
        };
        responses: {
            /** @description 迁移成功（已写入新配置并重建索引） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRootMigrateResponse"];
                };
            };
            /** @description 请求被拒绝：common_request_invalid / knowledge_root_mode_invalid / knowledge_root_target_invalid / knowledge_root_not_writable（原配置不变） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目标目录存在同名文件或文件夹，迁移已中止，原配置未变更（附 conflicts） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRootMigrateConflictError"];
                };
            };
            /** @description knowledge_root_migrate_failed（附 rollback）/ knowledge_root_set_failed（迁移已完成，未回滚）/ common_server_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRootMigrateFailedError"];
                };
            };
        };
    };
    scanKnowledge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 扫描完成 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int64
                         * @description 本次新增的文件夹数量
                         */
                        added_folders: number;
                        /**
                         * Format: int64
                         * @description 本次新增的文档数量
                         */
                        added_documents: number;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getDocumentPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 UUID */
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功（文档已删/文件缺失时 exists=false、absolute_path 为空） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPath"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                folder_id?: number;
                keyword?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Document"][];
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    createDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 文档标题（用于文件名，非法字符被转义） */
                    title: string;
                    /**
                     * Format: int64
                     * @description 父文件夹 ID，0 表示根
                     */
                    folder_id?: number;
                    /** @description 初始内容 */
                    content?: string;
                    tags?: string[];
                    /**
                     * @description 文档格式，默认 md
                     * @default md
                     * @enum {string}
                     */
                    ext?: "md" | "txt";
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description 请求非法（标题为空 / ext 非法） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 UUID */
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description 文档不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    updateDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 UUID */
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    /** Format: int64 */
                    folder_id?: number;
                    content?: string;
                    tags?: string[];
                    /** @description 冲突检测基准哈希 */
                    base_hash?: string;
                };
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description 文档不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 内容冲突（磁盘/基准哈希不一致） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        /** @example KNOWLEDGE_CONFLICT */
                        code?: string;
                        base_hash?: string;
                        current_hash?: string;
                        disk_hash?: string;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 UUID */
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已移入回收站 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        uuid?: string;
                        deleted?: boolean;
                    };
                };
            };
            /** @description 文档不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    restoreDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 UUID */
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 恢复成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        uuid?: string;
                        restored?: boolean;
                        /** Format: int64 */
                        updated_at?: number;
                    };
                };
            };
            404: components["responses"]["ServerError"];
        };
    };
    hardDeleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文档 UUID */
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 永久删除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        uuid?: string;
                        deleted?: boolean;
                        permanent?: boolean;
                    };
                };
            };
            /** @description 回收站中不存在该文档 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    listFolders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FolderNode"][];
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    createFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: int64 */
                    parent_id?: number;
                };
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderNode"];
                };
            };
            /** @description 名称不能为空 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    updateFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文件夹 ID */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    /** Format: int64 */
                    parent_id?: number;
                };
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        id?: number;
                        /** Format: int64 */
                        updated_at?: number;
                    };
                };
            };
            400: components["responses"]["ServerError"];
            /** @description 文件夹不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    deleteFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文件夹 ID */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    mode: "keep" | "purge";
                };
            };
        };
        responses: {
            /** @description 删除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        id: number;
                        /** @enum {string} */
                        mode: "keep" | "purge";
                        deleted: boolean;
                    };
                };
            };
            /** @description mode 非法 / 根文件夹不可删除 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 文件夹不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    listTrash: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Document"][];
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    searchKnowledge: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SearchResult"][];
                        /** Format: int64 */
                        total: number;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getConfigKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 配置键（如 knowledge_root_dir） */
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        value: string;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    putConfigKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 配置键（如 knowledge_root_dir） */
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: string;
                };
            };
        };
        responses: {
            /** @description 写入成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        key: string;
                        value: string;
                    };
                };
            };
            /** @description 请求体非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    spillTaskReferenceFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** Format: uuid */
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceSpillRequest"];
            };
        };
        responses: {
            /** @description 落盘成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceSpillResponse"];
                };
            };
            /** @description 请求被拒绝：localserver_reference_name_required / localserver_reference_content_required / 路径非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 任务不存在或任务目录未就绪：task_not_found / task_directory_empty */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description localserver_reference_write_failed：写盘失败或无法生成唯一文件名 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
