'use strict'

const { contextBridge, ipcRenderer } = require('electron')

// Sandboxed preload scripts only have Electron's limited CommonJS `require`.
// Keep the channel literal here instead of importing a local module, otherwise
// the preload fails before the bridge can be exposed to the renderer.
const SELECT_DIRECTORIES_CHANNEL = 'desktop:select-directories'
const OPEN_DIRECTORY_CHANNEL = 'desktop:open-directory'
const OPEN_TERMINAL_CHANNEL = 'desktop:open-terminal'
const OPEN_CODEX_THREAD_CHANNEL = 'desktop:open-codex-thread'
const GET_API_TOKEN_CHANNEL = 'desktop:get-api-token'
const GET_CLOSE_BEHAVIOR_CHANNEL = 'desktop:get-close-behavior'
const SET_CLOSE_BEHAVIOR_CHANNEL = 'desktop:set-close-behavior'
const SET_LOCALE_CHANNEL = 'desktop:set-locale'
const TRAY_STATUS_CHANNEL = 'desktop:tray-status'
const SHOW_TASK_NOTIFICATION_CHANNEL = 'desktop:show-task-notification'
const OPEN_TASK_CONVERSATION_CHANNEL = 'desktop:open-task-conversation'

const MAX_NOTIFICATION_TITLE_LENGTH = 120
const MAX_NOTIFICATION_BODY_LENGTH = 512
const MAX_NOTIFICATION_UUID_LENGTH = 128
const queuedOpenTaskConversations = []
const openTaskConversationListeners = new Set()

function normalizeNotificationText(value, maxLength) {
  return typeof value === 'string' ? value.trim().slice(0, maxLength) : ''
}

function normalizeTaskNotificationPayload(payload) {
  const title = normalizeNotificationText(payload?.title, MAX_NOTIFICATION_TITLE_LENGTH)
  const body = normalizeNotificationText(payload?.body, MAX_NOTIFICATION_BODY_LENGTH)
  const taskUuid = normalizeNotificationText(payload?.taskUuid, MAX_NOTIFICATION_UUID_LENGTH)
  const stepUuid = normalizeNotificationText(payload?.stepUuid, MAX_NOTIFICATION_UUID_LENGTH)
  if (!title || !body || !taskUuid) {
    throw new TypeError('Notification title, body and taskUuid are required')
  }
  return stepUuid ? { title, body, taskUuid, stepUuid } : { title, body, taskUuid }
}

function normalizeOpenTaskConversationPayload(payload) {
  const taskUuid = normalizeNotificationText(payload?.taskUuid, MAX_NOTIFICATION_UUID_LENGTH)
  const stepUuid = normalizeNotificationText(payload?.stepUuid, MAX_NOTIFICATION_UUID_LENGTH)
  if (!taskUuid) return null
  return stepUuid ? { taskUuid, stepUuid } : { taskUuid }
}

ipcRenderer.on(OPEN_TASK_CONVERSATION_CHANNEL, (_event, payload) => {
  const normalized = normalizeOpenTaskConversationPayload(payload)
  if (!normalized) return
  if (!openTaskConversationListeners.size) {
    queuedOpenTaskConversations.push(normalized)
    return
  }
  for (const listener of openTaskConversationListeners) {
    listener(normalized)
  }
})

contextBridge.exposeInMainWorld('goteamsDesktop', Object.freeze({
  platform: process.platform,
  /** @param {{ defaultPath?: string, multiple?: boolean }} options */
  selectDirectories(options = {}) {
    return ipcRenderer.invoke(SELECT_DIRECTORIES_CHANNEL, {
      defaultPath: typeof options.defaultPath === 'string' ? options.defaultPath : undefined,
      multiple: options.multiple === true,
    })
  },
  /** @param {string} directoryPath */
  openDirectory(directoryPath) {
    if (typeof directoryPath !== 'string') {
      return Promise.reject(new TypeError('Directory path must be a string'))
    }
    return ipcRenderer.invoke(OPEN_DIRECTORY_CHANNEL, directoryPath)
  },
  /** @param {string} directoryPath */
  openTerminal(directoryPath) {
    if (typeof directoryPath !== 'string') return Promise.reject(new TypeError('Directory path must be a string'))
    return ipcRenderer.invoke(OPEN_TERMINAL_CHANNEL, directoryPath)
  },
  /** @param {{ directoryPath: string, prompt: string, threadId?: string }} payload */
  openCodexThread(payload) {
    if (
      !payload ||
      typeof payload.directoryPath !== 'string' ||
      typeof payload.prompt !== 'string' ||
      (payload.threadId !== undefined && typeof payload.threadId !== 'string')
    ) {
      return Promise.reject(new TypeError('Codex thread payload is invalid'))
    }
    return ipcRenderer.invoke(OPEN_CODEX_THREAD_CHANNEL, {
      directoryPath: payload.directoryPath,
      prompt: payload.prompt,
      threadId: payload.threadId,
    })
  },
  /** Resolves to the startup API token generated by the Electron main process. */
  getApiToken() {
    return ipcRenderer.invoke(GET_API_TOKEN_CHANNEL)
  },
  getCloseBehavior() {
    return ipcRenderer.invoke(GET_CLOSE_BEHAVIOR_CHANNEL)
  },
  setCloseBehavior(closeBehavior) {
    return ipcRenderer.invoke(SET_CLOSE_BEHAVIOR_CHANNEL, closeBehavior)
  },
  /**
   * 把渲染层当前语言同步给主进程，用于托盘与原生对话框。
   * @param {string} locale
   */
  setLocale(locale) {
    if (typeof locale !== 'string') {
      return Promise.reject(new TypeError('Locale must be a string'))
    }
    return ipcRenderer.invoke(SET_LOCALE_CHANNEL, locale)
  },
  setTrayStatus(status = {}) {
    const count = Number.isFinite(status.runningTaskCount) ? Math.max(0, Math.floor(status.runningTaskCount)) : 0
    ipcRenderer.send(TRAY_STATUS_CHANNEL, { runningTaskCount: count })
  },
  showTaskNotification(payload) {
    try {
      return ipcRenderer.invoke(
        SHOW_TASK_NOTIFICATION_CHANNEL,
        normalizeTaskNotificationPayload(payload),
      )
    } catch (error) {
      return Promise.reject(error)
    }
  },
  onOpenTaskConversation(listener) {
    if (typeof listener !== 'function') {
      throw new TypeError('Task conversation listener must be a function')
    }
    while (queuedOpenTaskConversations.length) {
      listener(queuedOpenTaskConversations.shift())
    }
    openTaskConversationListeners.add(listener)
    return () => {
      openTaskConversationListeners.delete(listener)
    }
  },
}))
