'use strict'

const { contextBridge, ipcRenderer } = require('electron')

// Sandboxed preload scripts only have Electron's limited CommonJS `require`.
// Keep the channel literal here instead of importing a local module, otherwise
// the preload fails before the bridge can be exposed to the renderer.
const SELECT_DIRECTORIES_CHANNEL = 'desktop:select-directories'
const GET_API_TOKEN_CHANNEL = 'desktop:get-api-token'
const GET_CLOSE_BEHAVIOR_CHANNEL = 'desktop:get-close-behavior'
const SET_CLOSE_BEHAVIOR_CHANNEL = 'desktop:set-close-behavior'
const TRAY_STATUS_CHANNEL = 'desktop:tray-status'

contextBridge.exposeInMainWorld('goteamsDesktop', Object.freeze({
  platform: process.platform,
  /** @param {{ defaultPath?: string, multiple?: boolean }} options */
  selectDirectories(options = {}) {
    return ipcRenderer.invoke(SELECT_DIRECTORIES_CHANNEL, {
      defaultPath: typeof options.defaultPath === 'string' ? options.defaultPath : undefined,
      multiple: options.multiple === true,
    })
  },
  /** Resolves to the startup API token generated by the Electron main process. */
  getApiToken() {
    return ipcRenderer.invoke(GET_API_TOKEN_CHANNEL)
  },
  getCloseBehavior() {
    return ipcRenderer.invoke(GET_CLOSE_BEHAVIOR_CHANNEL)
  },
  setCloseBehavior(closeBehavior) {
    return ipcRenderer.invoke(SET_CLOSE_BEHAVIOR_CHANNEL, closeBehavior)
  },
  setTrayStatus(status = {}) {
    const count = Number.isFinite(status.runningTaskCount) ? Math.max(0, Math.floor(status.runningTaskCount)) : 0
    ipcRenderer.send(TRAY_STATUS_CHANNEL, { runningTaskCount: count })
  },
}))
