'use strict'

module.exports = Object.freeze({
  SELECT_DIRECTORIES: 'desktop:select-directories',
  OPEN_DIRECTORY: 'desktop:open-directory',
  OPEN_TERMINAL: 'desktop:open-terminal',
  OPEN_CODEX_THREAD: 'desktop:open-codex-thread',
  OPEN_VIBE_CLI: 'desktop:open-vibe-cli',
  GET_API_TOKEN: 'desktop:get-api-token',
  GET_CLOSE_BEHAVIOR: 'desktop:get-close-behavior',
  SET_CLOSE_BEHAVIOR: 'desktop:set-close-behavior',
  SET_LOCALE: 'desktop:set-locale',
  TRAY_STATUS: 'desktop:tray-status',
  SHOW_TASK_NOTIFICATION: 'desktop:show-task-notification',
  OPEN_TASK_CONVERSATION: 'desktop:open-task-conversation',
  UPDATE_STATE: 'desktop:update-state',
  UPDATE_CHECK: 'desktop:update-check',
  UPDATE_DEFER: 'desktop:update-defer',
  UPDATE_DOWNLOAD: 'desktop:update-download',
  UPDATE_CANCEL: 'desktop:update-cancel',
  UPDATE_INSTALL: 'desktop:update-install',
  UPDATE_CHANGED: 'desktop:update-changed',
  START_BROWSER_LOGIN: 'desktop:start-browser-login',
  BROWSER_LOGIN_RESULT: 'desktop:browser-login-result',
  RELAUNCH_APP: 'desktop:relaunch-app',
})
